<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>lk.jiat.bankauto</groupId>
        <artifactId>BankAuto</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>ear</artifactId>
    <packaging>ear</packaging>
    <name>bankauto-ear</name>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>lk.jiat.bankauto</groupId>
            <artifactId>account</artifactId>
            <version>1.0</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>lk.jiat.bankauto</groupId>
            <artifactId>auth</artifactId>
            <version>1.0</version>
            <type>ejb</type>
        </dependency>
        <dependency>
            <groupId>lk.jiat.bankauto</groupId>
            <artifactId>web</artifactId>
            <version>1.0</version>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <ejbModule>
                            <groupId>lk.jiat.bankauto</groupId>
                            <artifactId>auth</artifactId>
                            <bundleFileName>bankauto-auth-ejb.jar</bundleFileName>
                        </ejbModule>
                        <ejbModule>
                            <groupId>lk.jiat.bankauto</groupId>
                            <artifactId>account</artifactId>
                            <bundleFileName>bankauto-account-ejb.jar</bundleFileName>
                        </ejbModule>
                        <webModule>
                            <groupId>lk.jiat.bankauto</groupId>
                            <artifactId>web</artifactId>
                            <contextRoot>/bankauto</contextRoot>
                            <bundleFileName>web-module.war</bundleFileName>
                        </webModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>